name: sports-mercato
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit=1.28.0
  - pandas=2.0.3
  - plotly=5.15.0
  - numpy=1.24.3
  - matplotlib=3.7.2
  - pip
  - pip:
    - wordcloud==1.9.2
    - Pillow==10.0.1